### ISSUE TITLE
大佬这个调度器下的图有点像论文里的风格？如果是的话，可以求一下大佬的论文拜读拜读吗？感恩的心！

### ISSUE THREAD

**Issue by Peibohao** [adolphlwq/liang#1]
大佬这个调度器下的图有点像论文里的风格？如果是的话，可以求一下大佬的论文拜读拜读吗？感恩的心！

**Comment by alwqx** [comment]
大佬好眼光，这是我的毕业论文，论文放在issue2了，大佬自行下载吧

https://github.com/alwqx/liang/issues/2

**Comment by Peibohao** [comment]
> 大佬好眼光，这是我的毕业论文，论文放在issue2了，大佬自行下载吧
> 
> #2


献上感谢！

**Comment by alwqx** [comment]
fix
